GET http://localhost:4000/absensi

### get data hadir by id
GET http://localhost:4000/absensi/kehadiran/jumlah/20

### get data hadir by id
GET http://localhost:4000/absensi/kehadiran/data/23

### get data hadir by id
GET http://localhost:4000/absensi/kehadiran/detail/giri mekar/20

###
GET http://localhost:4000/absensi/hadir/20

###
GET http://localhost:4000/absensi/izin/20

### push data absen
POST http://localhost:4000/absensi
Content-Type: application/json

{
    "idAcara" : "20",
    "idAnggota" : "40530",  
    "status" : "hadir"
}

### PopupSubmit.jsx
POST http://localhost:4000/absensi/submit
Content-Type: application/json

{
    "acara" : "test",
    "idAcara" : "20",
    "kehadiran" : {
        "tets" : 12
    }
}

### ArsipAcara.jsx - not finished
GET http://localhost:4000/absensi/arsip