GET http://localhost:4000/absensi

###
GET http://localhost:4000/absensi/kehadiran/kelompok/20

###
GET http://localhost:4000/absensi/20

###
GET http://localhost:4000/absensi/izin/20

###
POST http://localhost:4000/absensi
Content-Type: application/json

{
    "idAcara" : "20",
    "idAnggota" : "40530",  
    "status" : "hadir"
}