GET http://localhost:4000/anggota   

###
GET http://localhost:4000/anggota/2

###
POST  http://localhost:4000/anggota   
Content-Type: application/json

{
    "nama" : "muhamad andika rafli",
    "noTelp" : "085624745579",
    "hobi" : "mengaji",
    "kelompok": "al-hikmah",
    "gender" : "pria",
    "ttl" : "2005-12-04"
}

###
DELETE  http://localhost:4000/anggota/1   